Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы

In [ ]:
import pandas as pd

In [ ]:
ratings = pd.read_csv('u.data.csv', header=None, delimiter='\t', names=['user_id', 'item_id', 'rating', 'timestamp'])
ratings.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [ ]:
movies = pd.read_csv('u.item.csv', header=None, delimiter='|', encoding='latin-1' , names=['movie_id', 'movie_title', 'release_date', 'video_release_date', 'IMDb_URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film_Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci_Fi', 'Thriller', 'War', 'Western'])
movies.head()

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Childrens,...,Fantasy,Film_Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок

In [ ]:
ratings['user_id'].value_counts().head(1)

405    737
Name: user_id, dtype: int64

Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь

In [ ]:
rating_405 = ratings[ratings['user_id'] == 405]
rating_405.head()

       user_id  item_id  rating  timestamp
12276      405       56       4  885544911
12383      405      592       1  885548670
12430      405     1582       1  885548670
12449      405      171       1  885549544
12460      405      580       1  885547447

Добавьте к датафрейму из задания 3 столбцы:

По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм принадлежит данному жанру и 0 - если нет

столбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей

In [ ]:
merged = pd.merge(left=rating_405, right=movies, how='inner', left_on='item_id', right_on='movie_id')
merged.head()

,user_id,item_id,rating,timestamp,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,...,Fantasy,Film_Noir,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western
0,405,56,4,885544911,56,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,...,0,0,0,0,0,0,0,0,0,0
1,405,592,1,885548670,592,True Crime (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,...,0,0,0,0,1,0,0,1,0,0
2,405,1582,1,885548670,1582,T-Men (1947),01-Jan-1947,NaN,http://us.imdb.com/M/title-exact?T-Men%20(1947),0,...,0,1,0,0,0,0,0,0,0,0
3,405,171,1,885549544,171,Delicatessen (1991),01-Jan-1991,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,...,0,0,0,0,0,0,1,0,0,0
4,405,580,1,885547447,580,"Englishman Who Went Up a Hill, But Came Down a...",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Englishman%20...,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
ratings_count = ratings[['rating', 'item_id']].groupby('item_id').count().reset_index()
ratings_count.head()

   item_id  rating
0        1     452
1        2     131
2        3      90
3        4     209
4        5      86

In [ ]:
ratings_count.rename(columns = {'rating': 'rating_count'}, inplace=True)
ratings_count.head()

   item_id  rating_count
0        1           452
1        2           131
2        3            90
3        4           209
4        5            86

In [ ]:
ratings_sum = ratings[['rating', 'item_id']].groupby('item_id').sum().reset_index()
ratings_sum.head()

   item_id  rating
0        1    1753
1        2     420
2        3     273
3        4     742
4        5     284

In [ ]:
ratings_sum.rename(columns = {'rating': 'rating_sum'}, inplace=True)
ratings_sum.head()

   item_id  rating_sum
0        1        1753
1        2         420
2        3         273
3        4         742
4        5         284

In [ ]:
two_ratings = ratings_count.merge(ratings_sum, how='inner')
two_ratings.head()

   item_id  rating_count  rating_sum
0        1           452        1753
1        2           131         420
2        3            90         273
3        4           209         742
4        5            86         284

In [ ]:
ratings_done = merged.merge(two_ratings, how='inner', left_on='item_id', right_on='item_id')
ratings_done.head()

,user_id,item_id,rating,timestamp,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,...,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western,rating_count,rating_sum
0,405,56,4,885544911,56,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,...,0,0,0,0,0,0,0,0,394,1600
1,405,592,1,885548670,592,True Crime (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,...,0,0,1,0,0,1,0,0,9,30
2,405,1582,1,885548670,1582,T-Men (1947),01-Jan-1947,NaN,http://us.imdb.com/M/title-exact?T-Men%20(1947),0,...,0,0,0,0,0,0,0,0,1,1
3,405,171,1,885549544,171,Delicatessen (1991),01-Jan-1991,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,...,0,0,0,0,1,0,0,0,65,252
4,405,580,1,885547447,580,"Englishman Who Went Up a Hill, But Came Down a...",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Englishman%20...,0,...,0,0,0,1,0,0,0,0,32,108

In [ ]:
ratings_done.drop('item_id', axis=1, inplace=True)
ratings_done.head()

,user_id,rating,timestamp,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,...,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western,rating_count,rating_sum
0,405,4,885544911,56,Pulp Fiction (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Pulp%20Fictio...,0,0,...,0,0,0,0,0,0,0,0,394,1600
1,405,1,885548670,592,True Crime (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?True%20Crime%...,0,0,...,0,0,1,0,0,1,0,0,9,30
2,405,1,885548670,1582,T-Men (1947),01-Jan-1947,NaN,http://us.imdb.com/M/title-exact?T-Men%20(1947),0,0,...,0,0,0,0,0,0,0,0,1,1
3,405,1,885549544,171,Delicatessen (1991),01-Jan-1991,NaN,http://us.imdb.com/M/title-exact?Delicatessen%...,0,0,...,0,0,0,0,1,0,0,0,65,252
4,405,1,885547447,580,"Englishman Who Went Up a Hill, But Came Down a...",01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Englishman%20...,0,0,...,0,0,0,1,0,0,0,0,32,108

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

Проведу небольшую подготовку данных.

Удалю ненужные столбцы, разделю дату и оставлю только год выпуска фильма.

In [ ]:
df_for_ml = ratings_done.drop(['user_id', 'timestamp', 'movie_id', 'movie_title', 'video_release_date', 'IMDb_URL'], axis=1)
df_for_ml.head()

,rating,release_date,unknown,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Horror,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western,rating_count,rating_sum
0,4,01-Jan-1994,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,394,1600
1,1,01-Jan-1995,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,9,30
2,1,01-Jan-1947,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
3,1,01-Jan-1991,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,65,252
4,1,01-Jan-1995,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,32,108

In [ ]:
df_for_ml[['day', 'month', 'year']] = df_for_ml['release_date'].str.split('-', 2, expand=True)

In [ ]:
df_for_ml.drop(['release_date', 'day', 'month'], axis=1, inplace=True)

In [ ]:
df_for_ml.head()

,rating,unknown,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,Drama,...,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western,rating_count,rating_sum,year
0,4,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,394,1600,1994
1,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,9,30,1995
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1947
3,1,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,65,252,1991
4,1,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,32,108,1995

In [ ]:
df_for_ml = df_for_ml.astype({'year': int}, errors='raise')
df_for_ml.dtypes

rating          int64
unknown         int64
Action          int64
Adventure       int64
Animation       int64
Childrens       int64
Comedy          int64
Crime           int64
Documentary     int64
Drama           int64
Fantasy         int64
Film_Noir       int64
Horror          int64
Musical         int64
Mystery         int64
Romance         int64
Sci_Fi          int64
Thriller        int64
War             int64
Western         int64
rating_count    int64
rating_sum      int64
year            int64
dtype: object

In [ ]:
df_for_ml.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737 entries, 0 to 736
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rating        737 non-null    int64
 1   unknown       737 non-null    int64
 2   Action        737 non-null    int64
 3   Adventure     737 non-null    int64
 4   Animation     737 non-null    int64
 5   Childrens     737 non-null    int64
 6   Comedy        737 non-null    int64
 7   Crime         737 non-null    int64
 8   Documentary   737 non-null    int64
 9   Drama         737 non-null    int64
 10  Fantasy       737 non-null    int64
 11  Film_Noir     737 non-null    int64
 12  Horror        737 non-null    int64
 13  Musical       737 non-null    int64
 14  Mystery       737 non-null    int64
 15  Romance       737 non-null    int64
 16  Sci_Fi        737 non-null    int64
 17  Thriller      737 non-null    int64
 18  War           737 non-null    int64
 19  Western       737 non-null    int64
 20  rating_count  737 non-null    int64
 21  rating_sum    737 non-null    int64
 22  year          737 non-null    int64
dtypes: int64(23)
memory usage: 154.4 KB

In [ ]:
X = df_for_ml.iloc[ :, 1:]
X.head()

,unknown,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,Drama,Fantasy,...,Musical,Mystery,Romance,Sci_Fi,Thriller,War,Western,rating_count,rating_sum,year
0,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,394,1600,1994
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,9,30,1995
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1947
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,65,252,1991
4,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,32,108,1995

In [ ]:
y= df_for_ml.iloc[ :, :1]
y.head()

   rating
0       4
1       1
2       1
3       1
4       1

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test, y_pred)

1.5350900470869757

Практика pyspark

In [ ]:
!apt-get update

Hit:1 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:7 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Ign:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:10 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:14 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,521 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,297 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,861 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,294 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1,006 kB]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [22.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1,040 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
Fetched 12.3 MB in 5s (2,509 kB/s)
Reading package lists... Done

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [ ]:
!wget -q https://downloads.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop2.7.tgz

In [ ]:
!tar -xvf spark-3.2.1-bin-hadoop2.7.tgz

spark-3.2.1-bin-hadoop2.7/
spark-3.2.1-bin-hadoop2.7/LICENSE
spark-3.2.1-bin-hadoop2.7/NOTICE
spark-3.2.1-bin-hadoop2.7/R/
spark-3.2.1-bin-hadoop2.7/R/lib/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/DESCRIPTION
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/INDEX
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/Rd.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/features.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/hsearch.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/links.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/nsInfo.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/Meta/package.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/NAMESPACE
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdb
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdx
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/AnIndex
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdb
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdx
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/aliases.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/help/paths.rds
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/00Index.html
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/html/R.css
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/general.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/profile/shell.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/testthat/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/daemon.R
spark-3.2.1-bin-hadoop2.7/R/lib/SparkR/worker/worker.R
spark-3.2.1-bin-hadoop2.7/R/lib/sparkr.zip
spark-3.2.1-bin-hadoop2.7/README.md
spark-3.2.1-bin-hadoop2.7/RELEASE
spark-3.2.1-bin-hadoop2.7/bin/
spark-3.2.1-bin-hadoop2.7/bin/beeline
spark-3.2.1-bin-hadoop2.7/bin/beeline.cmd
spark-3.2.1-bin-hadoop2.7/bin/docker-image-tool.sh
spark-3.2.1-bin-hadoop2.7/bin/find-spark-home
spark-3.2.1-bin-hadoop2.7/bin/find-spark-home.cmd
spark-3.2.1-bin-hadoop2.7/bin/load-spark-env.cmd
spark-3.2.1-bin-hadoop2.7/bin/load-spark-env.sh
spark-3.2.1-bin-hadoop2.7/bin/pyspark
spark-3.2.1-bin-hadoop2.7/bin/pyspark.cmd
spark-3.2.1-bin-hadoop2.7/bin/pyspark2.cmd
spark-3.2.1-bin-hadoop2.7/bin/run-example
spark-3.2.1-bin-hadoop2.7/bin/run-example.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-class
spark-3.2.1-bin-hadoop2.7/bin/spark-class.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-class2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-shell
spark-3.2.1-bin-hadoop2.7/bin/spark-shell.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-shell2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-sql
spark-3.2.1-bin-hadoop2.7/bin/spark-sql.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-sql2.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-submit
spark-3.2.1-bin-hadoop2.7/bin/spark-submit.cmd
spark-3.2.1-bin-hadoop2.7/bin/spark-submit2.cmd
spark-3.2.1-bin-hadoop2.7/bin/sparkR
spark-3.2.1-bin-hadoop2.7/bin/sparkR.cmd
spark-3.2.1-bin-hadoop2.7/bin/sparkR2.cmd
spark-3.2.1-bin-hadoop2.7/conf/
spark-3.2.1-bin-hadoop2.7/conf/fairscheduler.xml.template
spark-3.2.1-bin-hadoop2.7/conf/log4j.properties.template
spark-3.2.1-bin-hadoop2.7/conf/metrics.properties.template
spark-3.2.1-bin-hadoop2.7/conf/spark-defaults.conf.template
spark-3.2.1-bin-hadoop2.7/conf/spark-env.sh.template
spark-3.2.1-bin-hadoop2.7/conf/workers.template
spark-3.2.1-bin-hadoop2.7/data/
spark-3.2.1-bin-hadoop2.7/data/graphx/
spark-3.2.1-bin-hadoop2.7/data/graphx/followers.txt
spark-3.2.1-bin-hadoop2.7/data/graphx/users.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/
spark-3.2.1-bin-hadoop2.7/data/mllib/als/
spark-3.2.1-bin-hadoop2.7/data/mllib/als/sample_movielens_ratings.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/als/test.data
spark-3.2.1-bin-hadoop2.7/data/mllib/gmm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/license.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/54893.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/kittens/not-image.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/license.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/29.5.a_b_EGDP022204.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/not-image.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/54893.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP153539.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP802813.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA_alpha_60.png
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/chr30.4.184.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/grayscale.jpg
spark-3.2.1-bin-hadoop2.7/data/mllib/iris_libsvm.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/kmeans_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/pagerank_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/pic_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/ridge-data/
spark-3.2.1-bin-hadoop2.7/data/mllib/ridge-data/lpsa.data
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_fpgrowth.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_kmeans_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_lda_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_lda_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_libsvm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_linear_regression_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_movielens_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_multiclass_classification_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/sample_svm_data.txt
spark-3.2.1-bin-hadoop2.7/data/mllib/streaming_kmeans_data_test.txt
spark-3.2.1-bin-hadoop2.7/data/streaming/
spark-3.2.1-bin-hadoop2.7/data/streaming/AFINN-111.txt
spark-3.2.1-bin-hadoop2.7/examples/
spark-3.2.1-bin-hadoop2.7/examples/jars/
spark-3.2.1-bin-hadoop2.7/examples/jars/scopt_2.12-3.7.1.jar
spark-3.2.1-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.2.1.jar
spark-3.2.1-bin-hadoop2.7/examples/src/
spark-3.2.1-bin-hadoop2.7/examples/src/main/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.2.1-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java

In [ ]:
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

In [ ]:
# Загружаю датафреймы
ratings = spark.read.options(inferSchema='True', delimiter='\t').csv('u.data.csv')
ratings.show(5)

+---+---+---+---------+
|_c0|_c1|_c2|      _c3|
+---+---+---+---------+
|196|242|  3|881250949|
|186|302|  3|891717742|
| 22|377|  1|878887116|
|244| 51|  2|880606923|
|166|346|  1|886397596|
+---+---+---+---------+
only showing top 5 rows

In [ ]:
ratings = ratings.withColumnRenamed('_c0', 'user_id').withColumnRenamed('_c1', 'item_id').withColumnRenamed('_c2', 'rating').withColumnRenamed('_c3', 'timastamp')

In [ ]:
ratings.show(5)

+-------+-------+------+---------+
|user_id|item_id|rating|timastamp|
+-------+-------+------+---------+
|    196|    242|     3|881250949|
|    186|    302|     3|891717742|
|     22|    377|     1|878887116|
|    244|     51|     2|880606923|
|    166|    346|     1|886397596|
+-------+-------+------+---------+
only showing top 5 rows

In [ ]:
movies = spark.read.options(inferSchema='True', delimiter='|').csv('u.item.csv')
movies.show(5)

+---+-----------------+-----------+----+--------------------+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|_c0|              _c1|        _c2| _c3|                 _c4|_c5|_c6|_c7|_c8|_c9|_c10|_c11|_c12|_c13|_c14|_c15|_c16|_c17|_c18|_c19|_c20|_c21|_c22|_c23|
+---+-----------------+-----------+----+--------------------+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
|  1| Toy Story (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  1|  1|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  2| GoldenEye (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  1|  1|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
|  3|Four Rooms (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
|  4|Get Shorty (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  1|  0|  0|  0|   1|   0|   0|   1|   0|   0|   0|   0|   0|   0|   0|   0|   0|   0|
|  5|   Copycat (1995)|01-Jan-1995|null|http://us.imdb.co...|  0|  0|  0|  0|  0|   0|   1|   0|   1|   0|   0|   0|   0|   0|   0|   0|   1|   0|   0|
+---+-----------------+-----------+----+--------------------+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
only showing top 5 rows

In [ ]:
movies = movies.withColumnRenamed('_c0', 'movie_id').withColumnRenamed('_c1', 'movie_title').withColumnRenamed('_c2', 'release_date') \
               .withColumnRenamed('_c3', 'video_release_date').withColumnRenamed('_c4', 'IMDb_URL').withColumnRenamed('_c5', 'unknown') \
               .withColumnRenamed('_c6', 'Action').withColumnRenamed('_c7', 'Adventure').withColumnRenamed('_c8', 'AdveAnimationnture') \
               .withColumnRenamed('_c9', 'Childrens').withColumnRenamed('_c10', 'Comedy').withColumnRenamed('_c11', 'Crime') \
               .withColumnRenamed('_c12', 'Documentary').withColumnRenamed('_c13', 'Drama').withColumnRenamed('_c14', 'Fantasy') \
               .withColumnRenamed('_c15', 'Film_Noir').withColumnRenamed('_c16', 'Horror').withColumnRenamed('_c17', 'Musical') \
               .withColumnRenamed('_c18', 'Mystery').withColumnRenamed('_c19', 'Romance').withColumnRenamed('_c20', 'Sci_Fi') \
               .withColumnRenamed('_c21', 'Thriller').withColumnRenamed('_c22', 'War').withColumnRenamed('_c23', 'Western')

In [ ]:
movies.show(5)

+--------+-----------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie_id|      movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|AdveAnimationnture|Childrens|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+--------+-----------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|       1| Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 1|        1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       2| GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       3|Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       4|Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        0|                 0|        0|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       5|   Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
+--------+-----------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
# Средствами спарка вывести среднюю оценку для каждого фильма

In [ ]:
joined_df = ratings.join(movies,
               ratings.item_id == movies.movie_id,
               "inner")
joined_df.show(5)

+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|user_id|item_id|rating|timastamp|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|AdveAnimationnture|Childrens|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|    242|     3|881250949|     242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    186|    302|     3|891717742|     302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     22|    377|     1|878887116|     377| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    244|     51|     2|880606923|      51|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|    166|    346|     1|886397596|     346| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
joined_df.groupBy('movie_title').agg({'rating': 'avg'}).show()

+--------------------+------------------+
|         movie_title|       avg(rating)|
+--------------------+------------------+
|   Annie Hall (1977)| 3.911111111111111|
|Heavenly Creature...|3.6714285714285713|
|       Psycho (1960)| 4.100418410041841|
|Snow White and th...|3.7093023255813953|
|Night of the Livi...|          3.421875|
|When We Were King...| 4.045454545454546|
| If Lucy Fell (1996)|2.7586206896551726|
|    Fair Game (1995)|2.1818181818181817|
| Three Wishes (1995)|3.2222222222222223|
|         Cosi (1996)|               4.0|
|Paris, France (1993)|2.3333333333333335|
|Spanking the Monk...| 3.074074074074074|
|I'll Do Anything ...|               2.6|
|        Mondo (1996)|               3.0|
| Evil Dead II (1987)|3.5168539325842696|
|    Threesome (1994)| 2.838709677419355|
|Last Action Hero ...|2.7457627118644066|
|Reality Bites (1994)| 2.961038961038961|
|Colonel Chabert, ...|               3.5|
|   Blue Chips (1994)|2.6666666666666665|
+--------------------+------------------+
only showing top 20 rows

In [ ]:
# Посчитайте средствами спарка среднюю оценку для каждого жанра

In [ ]:
joined_df.show(5)

+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|user_id|item_id|rating|timastamp|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|AdveAnimationnture|Childrens|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|    242|     3|881250949|     242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    186|    302|     3|891717742|     302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     22|    377|     1|878887116|     377| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    244|     51|     2|880606923|      51|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|    166|    346|     1|886397596|     346| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
# AVG unknown
joined_df.where(joined_df.unknown == 1).groupBy('unknown').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Action
joined_df.where(joined_df.Action == 1).groupBy('Action').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Adventure
joined_df.where(joined_df.Adventure == 1).groupBy('Adventure').agg({'rating': 'avg'}).show()
print('------------------')
# AVG AdveAnimationnture
joined_df.where(joined_df.AdveAnimationnture == 1).groupBy('AdveAnimationnture').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Childrens
joined_df.where(joined_df.Childrens == 1).groupBy('Childrens').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Comedy
joined_df.where(joined_df.Comedy == 1).groupBy('Comedy').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Crime
joined_df.where(joined_df.Crime == 1).groupBy('Crime').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Documentary
joined_df.where(joined_df.Documentary == 1).groupBy('Documentary').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Drama
joined_df.where(joined_df.Drama == 1).groupBy('Drama').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Fantasy
joined_df.where(joined_df.Fantasy == 1).groupBy('Fantasy').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Film_Noir
joined_df.where(joined_df.Film_Noir == 1).groupBy('Film_Noir').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Horror
joined_df.where(joined_df.Horror == 1).groupBy('Horror').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Musical
joined_df.where(joined_df.Musical == 1).groupBy('Musical').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Mystery
joined_df.where(joined_df.Mystery == 1).groupBy('Mystery').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Romance
joined_df.where(joined_df.Romance == 1).groupBy('Romance').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Sci_Fi
joined_df.where(joined_df.Sci_Fi == 1).groupBy('Sci_Fi').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Thriller
joined_df.where(joined_df.Thriller == 1).groupBy('Thriller').agg({'rating': 'avg'}).show()
print('------------------')
# AVG War
joined_df.where(joined_df.War == 1).groupBy('War').agg({'rating': 'avg'}).show()
print('------------------')
# AVG Western
joined_df.where(joined_df.Western == 1).groupBy('Western').agg({'rating': 'avg'}).show()
print('------------------')

+-------+-----------+
|unknown|avg(rating)|
+-------+-----------+
|      1|        3.2|
+-------+-----------+

------------------
+------+-----------------+
|Action|      avg(rating)|
+------+-----------------+
|     1|3.480245417953027|
+------+-----------------+

------------------
+---------+-----------------+
|Adventure|      avg(rating)|
+---------+-----------------+
|        1|3.503526503308369|
+---------+-----------------+

------------------
+------------------+------------------+
|AdveAnimationnture|       avg(rating)|
+------------------+------------------+
|                 1|3.5766990291262135|
+------------------+------------------+

------------------
+---------+------------------+
|Childrens|       avg(rating)|
+---------+------------------+
|        1|3.3532442216652742|
+---------+------------------+

------------------
+------+------------------+
|Comedy|       avg(rating)|
+------+------------------+
|     1|3.3940734781442745|
+------+------------------+

------------------
+-----+------------------+
|Crime|       avg(rating)|
+-----+------------------+
|    1|3.6322780881440098|
+-----+------------------+

------------------
+-----------+------------------+
|Documentary|       avg(rating)|
+-----------+------------------+
|          1|3.6728232189973613|
+-----------+------------------+

------------------
+-----+------------------+
|Drama|       avg(rating)|
+-----+------------------+
|    1|3.6873793708484772|
+-----+------------------+

------------------
+-------+------------------+
|Fantasy|       avg(rating)|
+-------+------------------+
|      1|3.2152366863905324|
+-------+------------------+

------------------
+---------+------------------+
|Film_Noir|       avg(rating)|
+---------+------------------+
|        1|3.9215233698788228|
+---------+------------------+

------------------
+------+------------------+
|Horror|       avg(rating)|
+------+------------------+
|     1|3.2903893172841827|
+------+------------------+

------------------
+-------+-----------------+
|Musical|      avg(rating)|
+-------+-----------------+
|      1|3.521396851029471|
+-------+-----------------+

------------------
+-------+----------------+
|Mystery|     avg(rating)|
+-------+----------------+
|      1|3.63813155386082|
+-------+----------------+

------------------
+-------+-----------------+
|Romance|      avg(rating)|
+-------+-----------------+
|      1|3.621704948358255|
+-------+-----------------+

------------------
+------+------------------+
|Sci_Fi|       avg(rating)|
+------+------------------+
|     1|3.5607227022780834|
+------+------------------+

------------------
+--------+------------------+
|Thriller|       avg(rating)|
+--------+------------------+
|       1|3.5090069495245064|
+--------+------------------+

------------------
+---+-----------------+
|War|      avg(rating)|
+---+-----------------+
|  1|3.815811874866993|
+---+-----------------+

------------------
+-------+------------------+
|Western|       avg(rating)|
+-------+------------------+
|      1|3.6132686084142396|
+-------+------------------+

------------------

In [ ]:
# В спарке получить 2 датафрейма с 5-ю самыми популярными и самыми непопулярными фильмами (по количеству оценок, либо по самой оценке - на Ваш выбор)

In [ ]:
from pyspark.sql.functions import avg, desc

print('Top 5 movies')
joined_df.groupBy('movie_title').agg(avg('rating').alias('avg')).sort(desc('avg')).show(5)
print('---------------------')
print('Bot 5 movies')
joined_df.groupBy('movie_title').agg(avg('rating').alias('avg')).sort('avg').show(5)

Top 5 movies
+--------------------+---+
|         movie_title|avg|
+--------------------+---+
|     Star Kid (1997)|5.0|
|Marlene Dietrich:...|5.0|
|Great Day in Harl...|5.0|
|Someone Else's Am...|5.0|
|Saint of Fort Was...|5.0|
+--------------------+---+
only showing top 5 rows

---------------------
Bot 5 movies
+--------------------+---+
|         movie_title|avg|
+--------------------+---+
|        Gordy (1995)|1.0|
|Lashou shentan (1...|1.0|
|Modern Affair, A ...|1.0|
|3 Ninjas: High No...|1.0|
|JLG/JLG - autopor...|1.0|
+--------------------+---+
only showing top 5 rows

In [ ]:
# ml Linear Regression with PySpark

In [ ]:
from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler

In [ ]:
joined_df.columns

['user_id',
 'item_id',
 'rating',
 'timastamp',
 'movie_id',
 'movie_title',
 'release_date',
 'video_release_date',
 'IMDb_URL',
 'unknown',
 'Action',
 'Adventure',
 'AdveAnimationnture',
 'Childrens',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film_Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci_Fi',
 'Thriller',
 'War',
 'Western']

In [ ]:
joined_df.show(5)

+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|user_id|item_id|rating|timastamp|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|AdveAnimationnture|Childrens|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|    196|    242|     3|881250949|     242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    186|    302|     3|891717742|     302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|
|     22|    377|     1|878887116|     377| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|    244|     51|     2|880606923|      51|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|
|    166|    346|     1|886397596|     346| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 5 rows

In [ ]:
pipeline = Pipeline(stages=
                    [
                     VectorAssembler(inputCols=['unknown', 'Action', 'Adventure', 'AdveAnimationnture', 
                                                'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
                                                'Film_Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci_Fi', 'Thriller', 'War', 'Western'], outputCol="features")
                    ])

In [ ]:
piplineTrained = pipeline.fit(joined_df)

In [ ]:
joined_df = piplineTrained.transform(joined_df)
joined_df.show()

+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+--------------------+
|user_id|item_id|rating|timastamp|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|AdveAnimationnture|Childrens|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|            features|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+--------------------+
|    196|    242|     3|881250949|     242|        Kolya (1996)| 24-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[5],[1.0])|
|    186|    302|     3|891717742|     302|L.A. Confidential...| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    0|      0|        1|     0|      0|      1|      0|     0|       1|  0|      0|(19,[6,10,13,16],...|
|     22|    377|     1|878887116|     377| Heavyweights (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|(19,[4,5],[1.0,1.0])|
|    244|     51|     2|880606923|      51|Legends of the Fa...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  1|      1|(19,[8,14,17,18],...|
|    166|    346|     1|886397596|     346| Jackie Brown (1997)| 01-Jan-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|(19,[6,8],[1.0,1.0])|
|    298|    474|     4|884182806|     474|Dr. Strangelove o...| 01-Jan-1963|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  1|      0|(19,[15,17],[1.0,...|
|    115|    265|     2|881171488|     265|Hunt for Red Octo...| 01-Jan-1990|              null|http://us.imdb.co...|      0|     1|        0|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|(19,[1,16],[1.0,1...|
|    253|    465|     5|891628467|     465|Jungle Book, The ...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        1|                 0|        1|     0|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|(19,[2,4,14],[1.0...|
|    305|    451|     3|886324817|     451|       Grease (1978)| 01-Jan-1978|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      1|      0|      1|     0|       0|  0|      0|(19,[5,12,14],[1....|
|      6|     86|     3|883603013|      86|Remains of the Da...| 01-Jan-1993|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[8],[1.0])|
|     62|    257|     2|879372434|     257| Men in Black (1997)| 04-Jul-1997|              null|http://us.imdb.co...|      0|     1|        1|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|(19,[1,2,5,15],[1...|
|    286|   1014|     5|879781125|    1014|Romy and Michele'...| 25-Apr-1997|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[5],[1.0])|
|    200|    222|     5|876042340|     222|Star Trek: First ...| 22-Nov-1996|              null|http://us.imdb.co...|      0|     1|        1|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|(19,[1,2,15],[1.0...|
|    210|     40|     3|891035994|      40|To Wong Foo, Than...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[5],[1.0])|
|    224|     29|     3|888104457|      29|Batman Forever (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|                 0|        0|     1|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|(19,[1,2,5,6],[1....|
|    303|    785|     3|879485318|     785|     Only You (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|(19,[5,14],[1.0,1...|
|    122|    387|     5|879270459|     387|Age of Innocence,...| 01-Jan-1993|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[8],[1.0])|
|    194|    274|     2|879539794|     274|      Sabrina (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|(19,[5,14],[1.0,1...|
|    291|   1042|     4|874834944|    1042|   Just Cause (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      1|      0|     0|       1|  0|      0|(19,[13,16],[1.0,...|
|    234|   1184|     2|892079237|    1184|Endless Summer 2,...| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          1|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[7],[1.0])|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+--------------------+
only showing top 20 rows

In [ ]:
joined_df = joined_df.select(['features', 'rating'])
joined_df.show(5)

+--------------------+------+
|            features|rating|
+--------------------+------+
|      (19,[5],[1.0])|     3|
|(19,[6,10,13,16],...|     3|
|(19,[4,5],[1.0,1.0])|     1|
|(19,[8,14,17,18],...|     2|
|(19,[6,8],[1.0,1.0])|     1|
+--------------------+------+
only showing top 5 rows

In [ ]:
from pyspark.ml.regression import LinearRegression

In [ ]:
train, test = joined_df.randomSplit([0.8, 0.2], seed=42)

In [ ]:
lr = LinearRegression(featuresCol = 'features', labelCol='rating')
lr_model = lr.fit(train)

In [ ]:
trainingSummary = lr_model.summary
print("RMSE: %f" % trainingSummary.rootMeanSquaredError)
print("r2: %f" % trainingSummary.r2)

RMSE: 1.110754
r2: 0.029175

In [ ]:
test_pred = lr_model.transform(test)
test_pred.show(5)

+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+--------------------+------------------+
|user_id|item_id|rating|timastamp|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|AdveAnimationnture|Childrens|Comedy|Crime|Documentary|Drama|Fantasy|Film_Noir|Horror|Musical|Mystery|Romance|Sci_Fi|Thriller|War|Western|            features|        prediction|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+--------------------+------------------+
|      1|      3|     4|878542960|       3|   Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|     (19,[16],[1.0])| 3.407907413918345|
|      1|      7|     4|875071561|       7|Twelve Monkeys (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|(19,[8,15],[1.0,1...|3.7133037004016822|
|      1|      9|     5|878543541|       9|Dead Man Walking ...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|      (19,[8],[1.0])|3.6203553649073386|
|      1|     14|     5|874965706|      14|  Postino, Il (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|(19,[8,14],[1.0,1...|3.7353661587161806|
|      1|     20|     4|887431883|      20|Angels and Insect...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|                 0|        0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|(19,[8,14],[1.0,1...|3.7353661587161806|
+-------+-------+------+---------+--------+--------------------+------------+------------------+--------------------+-------+------+---------+------------------+---------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+--------------------+------------------+
only showing top 5 rows

In [ ]:
from pyspark.ml.evaluation import RegressionEvaluator

In [ ]:
lr_evaluator = RegressionEvaluator(predictionCol="prediction", \
                 labelCol="rating")
print("R Squared (R2) on test data = %g" % lr_evaluator.evaluate(test_pred))

R Squared (R2) on test data = 1.10914